### ISSUE TITLE
Investigate SQLAlchemy for SQL (and other) database interface for Tangelo

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/tangelo#375]

**Comment by ronichoudhury** [comment]
This is going to work out pretty well.  However, SQLAlchemy in particular offers an ORM-based approach.  I've developed a little example that shows how to go about using it, but it's not something that can or should be added to Tangelo as a plugin, since it's a very general technique that depends on the task at hand.  Instead, I think it makes more sense to start a developer cookbook with some guided examples of using different things, including SQLAlchemy.  Our existing examples could go in here possibly, and they could also be turned into blog posts as well.

So, I'm going to close this issue in favor of #472.
